[package]
name = "kvs"
version = "0.1.0"
description = "A key-value store"
edition = "2024"

[dependencies]
clap = "2.32.0"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
predicates = "1.0.0"
assert_cmd = "0.11.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
